### ISSUE TITLE
No driver in config hash errors out

### ISSUE THREAD

**Issue by virtuexru** [jibeinc/web_minion#31]
`driver = ruleset["config"]["driver"] || "mechanize"` in https://github.com/jibeinc/web_minion/blob/master/lib/web_minion/flow.rb:30 will error out `NoMethodError` if a driver key is not provided. Imho; this should default to the standard driver we use if theres no value passed in. Not supplying a proper driver should not break usage of webminion imo.

**Comment by stevendaniels** [comment]
I thought `ruleset["config"]`  is a required key. If that's the case, this won't cause an error.

**Comment by virtuexru** [comment]
You are right! Closing.
